#!/usr/bin/env python3
from math import sin, radians, tan
import argparse


def prett_print_inches(inches):

    s = str(inches).split('.')
    dec = ''
    
    try:
        dec = s[1]
    except:
        return 'NaN'

    cor = float('0.' + dec)
    
    if cor < 0.0625:
        return s[0]

    frac = ''
    
    frac = '⅞' if cor < 0.9375 else ''
    frac = '¾' if cor < 0.8125 else frac
    frac = '⅝' if cor < 0.6875 else frac
    frac = '½' if cor < 0.5625 else frac
    frac = '⅜' if cor < 0.4375 else frac
    frac = '¼' if cor < 0.3125 else frac
    frac = '⅛' if cor < 0.1875 else frac
    
    if frac == '':
        return str(int(s[0]) + 1)

    return s[0] + frac

# print the marks for conduits
def converge(dist_list, first_os, c, angle, first_mark):

	# get trig values
	tantheta = tan(radians(angle))
	sintheta = sin(radians(angle))
	
	
	# get offset size
	os_sizes = []
	for i in range(len(dist_list)):
		os_sizes.append(float(first_os + (i * c) - (dist_list[i] - dist_list[0]) ))

	# get distance b/w marks
	marks_dist = []	
	for i in os_sizes:
		marks_dist.append(i * (1/sintheta))

	# get f values for each item in dist_list and store in a list
	# f is defined as dist/tan(angle) - c/sin(angle), 
	# where dist =  dist_list[i] - dist_list[i-1]
	f_vals = [first_mark]
	for i in range(1, len(dist_list)):
		d = dist_list[i] - dist_list[i-1]
		f = (d / tantheta) - (c / sintheta)
		f_vals.append(f+f_vals[i-1])

	adjusted_starting_value = first_mark - min(f_vals)
	for i in range(len(f_vals)):
		f_vals[i] = f_vals[i] + adjusted_starting_value
		
	# print nicely
	for i in range(len(dist_list)):
		print("Conduit number",str(i+1) + ":\n")
		print("Mark 1: " + prett_print_inches(f_vals[i]))
		print("Mark 2: " + prett_print_inches(f_vals[i] + marks_dist[i]))	
		print("Offset size: " + prett_print_inches(os_sizes[i]))
		print("Distance between marks: " + prett_print_inches(marks_dist[i]) + "\n")

def main():
	# get values from argparse
	parser = argparse.ArgumentParser()
	
	
	parser.add_argument("-d", "--distances", nargs="+", required=True,
						help="<Required> list of the distances from the first conduit, starting with 0, in inches", type=float)

	parser.add_argument("-o", "--offset", required=True,
						help="<Required> distance of the first offset in inches", type=float)

	parser.add_argument("-a", "--angle", default=45.0,
						help="angle of the bend in degrees (default = 45)", type=float)

	parser.add_argument("-n", "--normalized", default=2.0,
						help="normalized centre-to-centre distance between conduits in inches (default = 2)", type=float)

	parser.add_argument("-f", "--first_mark", default=6.0,
						help="position of the smallest first mark in inches (default = 6.0)", type=float)

	#parser.add_argument("-q", "--quiet", 
						#help="set this flag to print with less info", action="store_true")

	args = parser.parse_args()

	converge(args.distances, args.offset, args.normalized, args.angle, args.first_mark)

main()
